{{- if and .Values.dash0.enabled .Values.dash0.syntheticChecks.enabled }}
apiVersion: operator.dash0.com/v1alpha1
kind: Dash0SyntheticCheck
metadata:
  name: {{ .Release.Name }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: synthetic-check
spec:
  display:
    name: "Frontend Availability"
  enabled: true
  notifications:
    channels: []
  plugin:
    kind: http
    spec:
      assertions:
        criticalAssertions:
          - kind: status_code
            spec:
              operator: lt
              value: "400"
        degradedAssertions: []
      request:
        method: get
        url: {{ .Values.dash0.syntheticChecks.frontendUrl | quote }}
        redirects: follow
        headers: []
        queryParameters: []
        tls:
          allowInsecure: false
        tracing:
          addTracingHeaders: true
  retries:
    kind: fixed
    spec:
      attempts: 2
      delay: 5s
  schedule:
    interval: 5m
    locations:
      {{- toYaml .Values.dash0.syntheticChecks.locations | nindent 6 }}
    strategy: all_locations
{{- end }}
