apiVersion: v1
kind: Secret
metadata:
  name: {{ include "anon-news.fullname" . }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "anon-news.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
type: Opaque
stringData:
  username: {{ .Values.postgres.auth.username | quote }}
  password: {{ .Values.postgres.auth.password | quote }}
