apiVersion: v1
kind: Service
metadata:
  name: {{ include "o11y-news.fullname" . }}-postgres-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "o11y-news.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "o11y-news.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "o11y-news.fullname" . }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "o11y-news.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "o11y-news.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
