'use client';

import { useState, useEffect, useRef, useCallback } from 'react';
import Link from 'next/link';

interface ArticleSection {
  heading?: string;
  paragraphs: string[];
}

interface HeroArticle {
  title: string;
  subtitle: string;
  sections: ArticleSection[];
}

interface Slide {
  videoId?: string;
  videoTitle?: string;
  heroImage?: string;  // path relative to /public, used when no video
  heroImageAlt?: string;
  category: string;
  headline: string[];
  tags: string[];
  // Embedded article (renders inline with preview + expand)
  article?: HeroArticle;
  // External blog fallback
  blogUrl?: string;
  blogSource?: string;
  blogTitle?: string;
  blogBlurb?: string;
}

const SLIDE_ARTICLE_1: HeroArticle = {
  title: 'The Derived Ontology: From Theory to Working Migrations',
  subtitle:
    'How a canonical ontology layer turned autonomous dashboard migration from theory into a working system across ELK, LGTM, and Dash0',
  sections: [
    {
      heading: 'From Concept to Proof',
      paragraphs: [
        'In January I wrote about ontologies for vendor-agnostic observability migration — the idea that a canonical semantic layer could bridge the conceptual gaps between platforms. That post was theory. This one is about what happened when we built it and pointed it at real infrastructure.',
        'The short version: we now have autonomous, AI-driven migration of dashboards and alert rules across three observability stacks — ELK (Elasticsearch/Kibana), LGTM (Loki/Grafana/Tempo/Mimir), and Dash0 — using derived ontological mappings that an AI agent traverses at runtime. Not scripts. Not templates. An agent that reads a source dashboard, understands what each panel means, and rebuilds it idiomatically on the target platform.',
        'The demo environment is a multi-cluster k3d setup running the OpenTelemetry Demo application, with identical instrumentation feeding all three stacks simultaneously. Same traces, same spans, same services. Three completely different ways of storing and querying them.',
      ],
    },
    {
      heading: 'The Derived Ontology',
      paragraphs: [
        "Rather than a static canonical model, we derived the ontology empirically. We stood up all three platforms against the same OTel data, then systematically mapped how each one represents the same underlying reality. The ontology isn't an abstract schema — it's a set of concrete translation rules extracted from observation.",
        'Take something as simple as "show me the error rate by service." Three platforms, three completely different expressions of the same concept:',
        'Kibana (KQL + Lens aggregations): A count operation type on an otel-traces* data view with a filter column where span.status.code: 2, broken down by a terms column on Resource.service.name.',
        'Grafana (PromQL against Mimir span metrics): sum by (service) (rate(traces_spanmetrics_calls_total{status_code="STATUS_CODE_ERROR"}[5m])). Note service not service_name, and STATUS_CODE_ERROR in SCREAMING_CASE.',
        'Dash0 (PromQL against OTel synthetic metrics): sum by (service_name) (rate({__name__="dash0.spans", otel_span_status_code="Error"}[$__rate_interval])). Note service_name, Title Case "Error", the __name__ selector syntax, and mandatory $__rate_interval.',
        'Same intent. Three different metric names, label keys, label values, query languages, and structural conventions. A syntactic converter would need to handle each pair independently — six translation paths for three platforms. The ontology reduces this to three mappings against a canonical concept: "error rate grouped by service identity."',
      ],
    },
    {
      heading: 'What the Mapping Actually Looks Like',
      paragraphs: [
        "The derived ontology isn't a single document. It's a layered system of translation tables that an AI agent consults during migration. Here's what we found we needed:",
        'Metric identity mapping. The same underlying data (OTel spans) surfaces as completely different metric names across platforms. Kibana doesn\'t have "metrics" at all — it queries raw span documents. Grafana\'s Mimir has traces_spanmetrics_calls_total generated by Tempo\'s span metrics processor. Dash0 synthesizes {__name__="dash0.spans"} at query time. Three paradigms: document store, derived counter, synthetic metric.',
        'Label key mapping. The service that emitted a span is Resource.service.name in Elasticsearch documents, service in Mimir span metrics labels, and service_name in Dash0. The service → service_name mapping between Grafana and Dash0 turned out to be the single most common migration error in testing — easy to miss, silent failure.',
        'Label value mapping. OTel span status codes appear as integer 2 in Elasticsearch, STATUS_CODE_ERROR in Mimir, and "Error" (Title Case) in Dash0. Wrong case returns zero results with no error. This is the kind of thing that burns hours in a manual migration and takes seconds to encode in an ontology.',
        'Structural mapping. Kibana Lens packs visualization config, query logic, and column definitions into a deeply nested JSON structure with layer IDs and operation types. Grafana uses flat PromQL strings with gridPos on each panel. Dash0 uses Perses CRDs with separate panels[] and layouts[] arrays, grid items referencing panels by index. The AI needs to understand all three structural idioms to translate between them.',
        'Query pattern mapping. increase(...[1h]) is idiomatic Grafana but invalid in Dash0\'s Perses context — you need rate(...[$__rate_interval]) * 3600. count in Kibana Lens is a document aggregation; in PromQL it\'s an entirely different operation. topk() works fine in Grafana but breaks Dash0 panels when the inner query returns no series.',
      ],
    },
    {
      heading: 'Gap Analysis in Practice',
      paragraphs: [
        'The original post predicted that gap detection would be the killer feature. It is.',
        'When migrating a Kibana dashboard that breaks spans down by span.name (operation name), the ontology flags: "span name is not available as a PromQL label in Dash0 — too-high cardinality. Substitute with http_route or rpc_method depending on protocol." The agent doesn\'t silently drop the panel or generate a broken query. It makes an informed substitution and documents the change.',
        "Similarly, Grafana's service graph metrics (traces_service_graph_request_total with client/server labels) have no equivalent in Dash0. The ontology maps this to RPC service/method groupings as the closest available approximation, and the gap is documented in the migration output.",
        "Some gaps we discovered weren't in the ontology theory at all — they're API-level behaviors that only surface through empirical testing:",
        "Dash0's dashboards_create API silently drops the layouts field. You must immediately follow creation with an update call containing the same payload. Without this, you get panel titles but empty tiles. No error, no warning. This took real debugging hours to discover and is now encoded in the migration skill so the agent handles it automatically every time.",
        "Dash0's check rule API uses otel_metric_name as the metric selector — not __name__. Dashboard PromQL uses __name__. Same platform, two different selector syntaxes for the same underlying metric. The ontology captures this distinction.",
        'Status code values in check rules are "ERROR" (uppercase), while in dashboard PromQL they\'re "Error" (Title Case). Same label, same platform, different casing depending on context.',
      ],
    },
    {
      heading: 'The Agent Architecture',
      paragraphs: [
        'The migration isn\'t a script. It\'s an AI agent equipped with MCP (Model Context Protocol) servers for each platform — Kibana, Elasticsearch, Grafana, and Dash0 — plus the derived ontology encoded as structured documentation the agent reads before executing.',
        'The workflow for a Kibana → Dash0 dashboard migration: The agent lists source dashboards via kibana_dashboards_list, presents options, and extracts the selected dashboard\'s full definition. It resolves data views to understand whether panels query spans or logs. Then — critically — it samples live data from the Dash0 environment via dash0_spans_query to confirm which labels actually exist in the target before building any panels.',
        'For each Kibana Lens panel, the agent reads the visualization type (XY, pie, metric, table), the operation types (count, average, percentile, terms), the source fields, and any filters. It maps each element through the ontology: Lens lnsXY becomes TimeSeriesChart, a count operation on traces becomes sum(rate({__name__="dash0.spans"}[$__rate_interval])), a terms breakdown on service.name becomes a by (service_name) clause.',
        'The agent assembles the Perses CRD, handles the two-step create-then-update dance, and verifies the result. If panels show "no data," it can query Dash0\'s live span data to diagnose the issue — wrong label name, wrong case, missing filter — and fix it autonomously.',
        'The same architecture handles Grafana → Dash0 with different translation tables. The LGTM metric names, label keys, and query patterns map through the same canonical concepts to different Dash0 expressions.',
      ],
    },
    {
      heading: 'What We Learned',
      paragraphs: [
        'The ontology is never complete on the first pass. We started with theoretical mappings and refined them through actual migration attempts. Every "no data" panel in the target platform exposed a mapping gap we hadn\'t anticipated. The 21 "hard-won lessons" documented in our migration skills are battle scars from this process.',
        'Label cardinality determines what\'s possible. High-cardinality fields like span name and span kind are available in Kibana (document-level queries) but absent from PromQL-based platforms where they\'d create metric explosion. The ontology must encode these availability boundaries, not just name mappings.',
        'API behavior matters as much as data model. The layouts silently dropping, the __name__ vs otel_metric_name split, the case sensitivity of status code values — these are implementation details that no theoretical ontology would predict. They only emerge from empirical testing and must be captured for autonomous operation.',
        "Log severity is sparser than you expect. Many services write raw stdout logs without OTel severity metadata. A dashboard that segments logs by severity will show nothing for most services. The ontology now defaults to total log volume by service, using severity breakdowns only when confirmed present in the target environment.",
        "The two-platform problem is deceptive. Going from Kibana to Dash0 requires one mapping. Adding Grafana as a source requires a second, largely independent mapping — the LGTM stack's data model differs from both ELK and Dash0. But once you have both, you also implicitly have Kibana → Grafana (which we built separately and validated). The ontology's value compounds as platforms are added.",
      ],
    },
    {
      heading: 'What This Means for Observability Consulting',
      paragraphs: [
        'Traditional migration engagements rely on senior engineers manually inspecting source configurations, understanding intent, and rebuilding in the target platform. It works, but it\'s slow and the quality depends entirely on who\'s doing the work.',
        'With the derived ontology and agent architecture, the mechanical translation is automated. The 22-panel dashboard migration that would take a consultant a day completes in minutes. The consultant\'s expertise focuses on the gaps — the panels that can\'t translate cleanly, the architectural decisions about what to substitute, the trade-offs between fidelity and capability.',
        'This isn\'t "AI replaces the consultant." It\'s "AI handles the conversion work so the consultant focuses on the decisions that actually require judgment." The ontology surfaces those decisions explicitly rather than leaving them buried in implementation details that might not be discovered until production.',
        "The migration skills and ontological mappings are living documents. Every new engagement, every new platform version, every edge case feeds back into the system. The agent gets better at migration the same way a consulting team builds institutional knowledge — except the knowledge is encoded, reproducible, and doesn't walk out the door.",
      ],
    },
  ],
};

const SLIDE_ARTICLE_2: HeroArticle = {
  title: 'The Spatial Signal: Observability on Apple Vision Pro',
  subtitle:
    'VALISSpatial renders distributed traces, service topology, and latency metrics as navigable 3D environments — and connects to the same MCP servers that power VALIS',
  sections: [
    {
      heading: 'Why 2D Breaks Down',
      paragraphs: [
        "Every observability dashboard eventually hits the same wall. You can add more panels, more rows, more tabs — but the fundamental constraint is the same: a flat rectangle on a flat screen. The mental model required to understand how a request propagates through eight microservices, across three namespaces, under degraded network conditions, is inherently three-dimensional. We compress it into tables and node graphs and hope engineers can mentally reconstruct the spatial relationships that determine whether a system is healthy.",
        "The premise behind VALISSpatial is straightforward: stop compressing. Render the system as it actually exists — a graph of interdependent services occupying space — and let engineers navigate it directly. Apple Vision Pro provides the first consumer device capable of doing this without the friction that killed earlier AR attempts. Passthrough at 4K, eye tracking with sub-millimeter precision, and native visionOS depth compositing means the rendering feels anchored to the room, not floating in a headset.",
        "This is an early demo. The rendering is production code; the data pipeline is still being wired. But the core experience — floating service nodes, glowing dependency edges, latency bar charts rising from the floor — is fully implemented and running against live Dash0 telemetry.",
      ],
    },
    {
      heading: 'What the Immersive Space Renders',
      paragraphs: [
        "When you enter the immersive space, VALISSpatial places a force-directed service topology graph at eye level — nodes distributed across an oval roughly 2.1 meters in front of you, arranged by a 25-iteration relaxation algorithm that balances repulsion between services against the attraction of traced call edges.",
        "Each node is a sphere with an emissive glow shell. The color encodes error rate: teal for healthy (≤1% errors), amber for warning (1–5%), coral red for critical (above 5%). The glow intensity scales with the error rate, so degraded services pulse visibly at the periphery of your vision. Edges are glowing cylinders between parent and child services, thickness proportional to call volume, with directional cones marking the target service.",
        "Below the topology, at floor level, an arc of 3D bar charts renders per-service latency. X-axis is time, Y-axis is duration capped at 2000ms to prevent outliers from collapsing the scale. The same teal-amber-coral palette maps to latency thresholds, so a service going orange in the topology corresponds to bars going orange in its chart directly below.",
        "Tapping a node opens a floating detail panel anchored beside it — span count, average latency, error rate, error count, top operations by volume. The Fly Traces feature finds the busiest distributed trace in the current snapshot and animates through it service by service: 1.3 seconds of smooth camera movement to each node, 1.4 seconds of dwell, 2.5 seconds of detail panel, then on to the next hop in the chain. Watching a checkout flow traverse frontend → cart → payment → order → email in real space is qualitatively different from following arrows on a service map.",
      ],
    },
    {
      heading: 'MCP as the Data Layer',
      paragraphs: [
        "VALISSpatial's data architecture mirrors the approach taken in the VALIS MCP server: a vendor-agnostic provider protocol layered over platform-specific MCP clients. The ObservabilityProvider protocol defines three methods — fetchSpans, fetchLogs, fetchMetrics — that every backend implements identically regardless of the source platform.",
        "The Dash0 provider is fully implemented. It calls dash0_spans_query and dash0_logs_query via a lightweight JSON-RPC 2.0 client (no external SDK dependency — written against the MCP specification directly). The Dynatrace and Datadog providers are stubs awaiting the corresponding backend MCP servers. When those ship, wiring them into VALISSpatial is a single conformance implementation — the 3D rendering layer never changes.",
        "This matters because the goal isn't a Dash0 visualization app or a Dynatrace visualization app. It's an observability visualization layer that works across whatever platforms an organization actually runs. The MCP abstraction makes that possible without rebuilding the renderer for every vendor.",
        "For demos and development, a MockProvider generates synthetic telemetry for six services with configurable error rates, and a FileProvider loads pre-recorded Dash0 JSON exports from disk. This means the full immersive experience runs without any live infrastructure — useful for workshops, sales demos, and iteration without cluster access.",
      ],
    },
    {
      heading: 'Connecting to VALIS',
      paragraphs: [
        "The longer-term architecture connects VALISSpatial to VALIS — the Go-based MCP server that already speaks to Dynatrace, Dash0, and a local ClickHouse cluster. VALIS has baseline calibration (EWMA-smoothed per-service thresholds across request rate, error rate, and duration), anomaly detection, and the same vendor-agnostic span normalization that VALISSpatial needs.",
        "In that configuration, VALISSpatial becomes the spatial front-end for VALIS's analytical backend. Instead of rendering raw spans, it renders VALIS findings: services deviating from baseline shown in the topology graph, anomaly severity encoded in glow intensity, baseline comparison bars overlaid on the latency charts. The Fly Traces feature becomes a guided tour of the current highest-severity incident, moving through services in order of anomaly score rather than raw span volume.",
        "This isn't speculative — the interfaces already exist on both sides. VALISSpatial's ObservabilityProvider protocol maps cleanly to VALIS's normalized span format. The work is the glue: a VALISProvider implementation that calls the VALIS HTTP API and translates the response. The spatial rendering doesn't change at all.",
      ],
    },
    {
      heading: 'What This Changes',
      paragraphs: [
        "The standard case for spatial computing in enterprise software is questionable. Most workflows don't benefit from being in 3D space. Calendar management, code review, document editing — these are fine on a flat screen. Distributed systems observability is the exception.",
        "A microservice architecture has genuine spatial structure. Services have proximity (which ones call which), depth (hot paths vs. cold paths), and topology (fan-out, fan-in, critical paths). The relationships that matter for understanding incidents — dependency chains, error propagation paths, cascading latency — are inherently graph-shaped. When you render that graph in the room and can physically walk around it, the spatial memory you form is different from the abstract understanding you build from a 2D diagram. You remember where the payment service sits relative to the fraud check service. You remember that the database nodes cluster in the back-left. When an incident happens, you orient to the topology instead of scanning panels.",
        "VALISSpatial is a demo. It's not in production anywhere. But it represents a direction that becomes more credible as the device generation matures and the data pipelines get wired. The MCP protocol layer means the visualization infrastructure is already vendor-agnostic. The question is whether the spatial medium earns its place as a genuinely useful tool for on-call engineers — and whether the answer changes when the rendering is connected to real-time anomaly detection rather than raw spans.",
        "That's what we're building toward.",
      ],
    },
  ],
};

const SLIDE_ARTICLE_3: HeroArticle = {
  title: 'ClickHouse on a Raspberry Pi 5: A Surprisingly Capable Observability Backend',
  subtitle:
    '228 million rows of OpenTelemetry data compressed to 1.37 GiB — on a $120 board running k3s, ArgoCD, Grafana, and custom OTel receivers simultaneously',
  sections: [
    {
      heading: 'The Hardware',
      paragraphs: [
        "There's a recurring assumption in the observability world that serious analytical databases need serious hardware — a fat EC2 instance, a managed cloud offering, or at minimum a beefy on-prem server. I've been quietly running ClickHouse on a Raspberry Pi 5 for several months, and the numbers are compelling enough to write down.",
        "The board is a Raspberry Pi 5 Model B Rev 1.1, running Ubuntu 24.04.3 LTS on aarch64. 16 GB LPDDR4X RAM, quad-core ARM Cortex-A76 at 2.4 GHz. The key upgrade is a ~917 GB NVMe SSD via M.2 HAT+ on the Pi 5's PCIe 2.0 lane. Without fast storage, ClickHouse's write throughput would be the obvious bottleneck. With the SSD, disk is never a concern. Total cost of board + HAT + SSD: roughly $120–150 depending on the SSD you pick. It also serves as a NAS via Samba. It's doing a lot.",
      ],
    },
    {
      heading: 'ClickHouse: 228 Million Rows',
      paragraphs: [
        "ClickHouse 25.10.2.65 (official ARM64 build) runs natively via apt, managed by systemd. No Docker — direct host install for maximum I/O performance. Uptime at time of writing: 22 days, 8 hours. No restarts, no babysitting.",
        "The otel database holds the full OpenTelemetry schema plus a custom unifi_metrics table: 192 million metric rows at 824 MB, 10.3 million trace spans at 362 MB, 5.4 million log records at 138 MB — 228 million total rows in 1.37 GiB on disk. 192 million metric data points compressed to 824 MB. That's the ClickHouse value proposition in one row.",
        "One trip hazard worth calling out: if you install ClickHouse and walk away, the system log tables will quietly eat your disk. system.trace_log alone consumed 47.98 GiB; system.text_log another 5.34 GiB. Fix this immediately after install by setting TTL policies on each system log table in config.xml. Tame these early — they're the most common homelab ClickHouse mistake.",
      ],
    },
    {
      heading: 'k3s, ArgoCD, and a GitOps Loop on $120',
      paragraphs: [
        "k3s is the right Kubernetes distribution for single-node ARM deployments — full conformant Kubernetes under 100 MB, SQLite instead of etcd, tiny memory footprint. The cluster has been running for 83 days with only 4 pod restarts, all graceful. ArgoCD runs inside k3s — all 7 components — and manages a single Application: the custom OTel collector.",
        "GitLab pushes a new image → GitLab Runner (also running on the Pi) builds it → ArgoCD detects the change and rolls out the new deployment. The whole CI/CD loop runs on the same $120 board it's deploying to. That's a satisfying kind of bootstrapping. Grafana runs directly on the host, reading from ClickHouse over localhost via the Grafana ClickHouse plugin. PostgreSQL 16 serves as Grafana's metadata store. Both managed by systemd.",
      ],
    },
    {
      heading: 'The Custom OTel Collector',
      paragraphs: [
        "The collector running in k3s isn't stock otelcol-contrib — it's a custom binary built with the OpenTelemetry Collector Builder, including receivers I wrote specifically for my home network.",
        "unifireceiver scrapes the UniFi Dream Machine's API every 30 seconds, producing VAP-level metrics per access point, per SSID, per radio band: tx/rx bytes and packets, error and drop rates, connected client counts, connection quality scores (CCQ), average RSSI, Dream Machine temperature, switch port throughput, and WAN health. The unifi_metrics table now holds 436,640+ rows. Each scrape produces ~2,000 data points. The network picture this gives is surprisingly complete.",
        "airflowreceiver pulls DAG run metrics and pool utilization from Apache Airflow. githubreceiver tracks repository activity from the GitHub API — contribution velocity and open issue counts over time. hostmetrics collects the Pi's own system metrics at process granularity: ~850 metrics per scrape cycle from process-level CPU and memory collection alone. The standard otlp receiver listens on gRPC :4317 and HTTP :4318 for any application that wants to push telemetry locally. An OpAMP supervisor is wired in for future remote config management without touching ArgoCD.",
      ],
    },
    {
      heading: 'Is a Pi 5 Enough?',
      paragraphs: [
        "For a homelab observability stack? Absolutely. 22+ days of zero-maintenance runtime. 228 million rows of OTel data in 1.37 GiB on disk. 2,000+ metrics per 30-second scrape from UniFi alone. Full k3s, ArgoCD, Grafana, and GitLab Runner running in parallel. The Pi 5's ARM Cortex-A76 cores are legitimately fast — ClickHouse's vectorized execution engine translates to ARM NEON SIMD instructions and performs well.",
        "Where you'll hit limits: very high cardinality workloads, or environments where you need the in-memory analytics that larger machines enable. For home network monitoring, distributed tracing from a handful of services, and general infrastructure observability, the Pi 5 has not been the bottleneck once. The real bottleneck is always your own time configuring it — which is also true of every other observability setup I've ever built.",
      ],
    },
  ],
};

// Add more slides here when new videos are published
const SLIDES: Slide[] = [
  {
    videoId: 'hlS44t0_z0M',
    videoTitle: 'Agentic Workflow — Kibana to Grafana Dashboard Migration',
    category: 'Observability · Platform Engineering',
    headline: ['THE DERIVED', 'ONTOLOGY:', 'MIGRATIONS AT SCALE'],
    tags: ['OpenTelemetry', 'Agentic AI', 'Platform Migration', 'MCP'],
    article: SLIDE_ARTICLE_1,
  },
  {
    videoId: 'RbMr4FxdZyU',
    videoTitle: 'VALISSpatial — Observability on Apple Vision Pro',
    category: 'Spatial Computing · Observability',
    headline: ['THE', 'SPATIAL', 'SIGNAL'],
    tags: ['Apple Vision Pro', 'visionOS', 'MCP', 'OpenTelemetry', 'Spatial Computing'],
    article: SLIDE_ARTICLE_2,
  },
  {
    heroImage: '/pi5-homelab.jpg',
    heroImageAlt: 'Raspberry Pi 5 single-board computer',
    category: 'Homelab · Edge Computing',
    headline: ['228M ROWS', 'ON $120', 'HARDWARE'],
    tags: ['ClickHouse', 'Raspberry Pi 5', 'k3s', 'OpenTelemetry', 'Homelab'],
    article: SLIDE_ARTICLE_3,
  },
];

const SIDEBAR_CARDS = [
  {
    icon: '🔭',
    title: 'LIVE TELEMETRY',
    description: 'Real-time traces and metrics from this running application.',
    cta: 'Explore →',
    href: '/telemetry',
    external: false,
  },
  {
    icon: '🔍',
    title: 'KIBANA MCP',
    description: 'Full-surface MCP server for Kibana — dashboards, alerts, saved objects, Lens, and KQL query execution.',
    cta: 'View on GitHub →',
    href: 'https://github.com/npcomplete777/Kibana-mcp',
    external: true,
  },
  {
    icon: '🔎',
    title: 'ELASTICSEARCH MCP',
    description: 'MCP server for Elasticsearch — index management, document search, cluster health, and aggregation queries.',
    cta: 'View on GitHub →',
    href: 'https://github.com/npcomplete777/ElasticSearch-mcp',
    external: true,
  },
  {
    icon: '📡',
    title: 'DASH0 MCP',
    description: 'MCP server for Dash0 — spans, logs, metrics, dashboards, check rules, and synthetic monitoring.',
    cta: 'View on GitHub →',
    href: 'https://github.com/npcomplete777/Dash0-mcp',
    external: true,
  },
  {
    icon: '📈',
    title: 'GRAFANA MCP',
    description: 'MCP server for Grafana — dashboard creation, PromQL/Loki queries, alert rules, and datasource management.',
    cta: 'View on GitHub →',
    href: 'https://github.com/npcomplete777/Grafana-mcp',
    external: true,
  },
  {
    icon: '🦋',
    title: 'DYNATRACE CLASSIC MCP',
    description: 'MCP server for Dynatrace Classic — entities, problems, metrics, USQL queries, and Davis AI integration.',
    cta: 'View on GitHub →',
    href: 'https://github.com/npcomplete777/Dynatrace-classic-v2-mcp',
    external: true,
  },
  {
    icon: '🦋',
    title: 'DYNATRACE PLATFORM MCP',
    description: 'MCP server for Dynatrace Platform — DQL queries, log analytics, business events, and platform APIs.',
    cta: 'View on GitHub →',
    href: 'https://github.com/npcomplete777/Dynatrace-platform-mcp',
    external: true,
  },
  {
    icon: '🐶',
    title: 'DATADOG MCP',
    description: 'MCP server for Datadog — metrics, logs, traces, monitors, dashboards, and incident management.',
    cta: 'View on GitHub →',
    href: 'https://github.com/npcomplete777/Datadog-mcp',
    external: true,
  },
  {
    icon: '⚙️',
    title: 'APPDYNAMICS MCP',
    description: 'MCP server for AppDynamics — application performance, business transactions, baselines, and anomaly detection.',
    cta: 'View on GitHub →',
    href: 'https://github.com/npcomplete777/AppD-mcp',
    external: true,
  },
  {
    icon: '⚡',
    title: 'SOURCE CODE',
    description: 'Full-stack Kubernetes app: Next.js, Spring Boot, OTel Java agent.',
    cta: 'View on GitHub →',
    href: 'https://github.com/npcomplete777/my-news-k8s',
    external: true,
  },
];

const INTERVAL_MS = 5000;
const PREVIEW_PARAGRAPHS = 2;

function InlineArticle({ article }: { article: HeroArticle }) {
  const [expanded, setExpanded] = useState(false);

  const previewParas = article.sections[0]?.paragraphs.slice(0, PREVIEW_PARAGRAPHS) ?? [];

  return (
    <div className="border-t border-stone-200 pt-4 dark:border-zinc-800">
      {/* Header */}
      <div className="mb-3 flex flex-col gap-1">
        <span className="text-[10px] font-bold uppercase tracking-widest text-stone-400 dark:text-zinc-500">
          Featured Article · O11y Alchemy
        </span>
        <h2 className="text-base font-black uppercase tracking-tight text-stone-900 dark:text-zinc-100 sm:text-lg">
          {article.title}
        </h2>
        <p className="text-xs font-medium italic text-stone-500 dark:text-zinc-500">
          {article.subtitle}
        </p>
      </div>

      {/* Collapsed preview */}
      {!expanded && (
        <div className="flex flex-col gap-3">
          {previewParas.map((para, i) => (
            <p key={i} className="text-sm leading-relaxed text-stone-600 dark:text-zinc-400">
              {para}
            </p>
          ))}
          <button
            type="button"
            onClick={() => setExpanded(true)}
            className="mt-1 self-start text-xs font-bold uppercase tracking-widest text-stone-900 underline underline-offset-4 transition-colors hover:text-stone-500 dark:text-zinc-100 dark:hover:text-zinc-400"
          >
            Read full article ↓
          </button>
        </div>
      )}

      {/* Expanded full article */}
      {expanded && (
        <div className="flex flex-col gap-6">
          {article.sections.map((section, si) => (
            <div key={si} className="flex flex-col gap-3">
              {section.heading && (
                <h3 className="text-xs font-black uppercase tracking-widest text-stone-900 dark:text-zinc-100">
                  {section.heading}
                </h3>
              )}
              {section.paragraphs.map((para, pi) => (
                <p key={pi} className="text-sm leading-relaxed text-stone-600 dark:text-zinc-400">
                  {para}
                </p>
              ))}
            </div>
          ))}
          <button
            type="button"
            onClick={() => setExpanded(false)}
            className="self-start text-xs font-bold uppercase tracking-widest text-stone-400 underline underline-offset-4 transition-colors hover:text-stone-900 dark:text-zinc-500 dark:hover:text-zinc-100"
          >
            Collapse ↑
          </button>
        </div>
      )}
    </div>
  );
}

export function HeroCarousel() {
  const [current, setCurrent] = useState(0);
  const [playing, setPlaying] = useState(false);
  const [paused, setPaused] = useState(false);
  const [progressKey, setProgressKey] = useState(0);
  const timerRef = useRef<ReturnType<typeof setTimeout>>(null);

  const advance = useCallback((dir: number) => {
    setCurrent((c) => (c + dir + SLIDES.length) % SLIDES.length);
    setPlaying(false);
    setProgressKey((k) => k + 1);
  }, []);

  const goTo = useCallback((idx: number) => {
    setCurrent(idx);
    setPlaying(false);
    setProgressKey((k) => k + 1);
  }, []);

  useEffect(() => {
    if (paused || playing) return;
    timerRef.current = setTimeout(() => advance(1), INTERVAL_MS);
    return () => {
      if (timerRef.current) clearTimeout(timerRef.current);
    };
  }, [current, paused, playing, progressKey, advance]);

  const slide = SLIDES[current];
  const thumbnailUrl = slide.videoId
    ? `https://img.youtube.com/vi/${slide.videoId}/maxresdefault.jpg`
    : '';

  return (
    <section
      className="grid grid-cols-1 gap-10 py-10 lg:grid-cols-[1fr_300px]"
      onMouseEnter={() => setPaused(true)}
      onMouseLeave={() => setPaused(false)}
    >
      {/* Left column */}
      <div className="flex flex-col gap-6">

        {/* Slide nav cards — magazine-style navigation */}
        <div className="flex gap-0 border-t border-stone-200 dark:border-zinc-800">
          {SLIDES.map((s, i) => {
            const isActive = i === current;
            return (
              <button
                key={i}
                type="button"
                onClick={() => goTo(i)}
                className={`group relative flex-1 overflow-hidden py-3 pr-4 text-left transition-colors
                  ${i > 0 ? 'border-l border-stone-200 pl-4 dark:border-zinc-800' : ''}
                  ${isActive ? '' : 'hover:bg-stone-50 dark:hover:bg-zinc-900/50'}`}
                aria-label={`Go to slide ${i + 1}`}
              >
                {/* Active top-border progress bar */}
                {isActive && (
                  <span
                    key={progressKey}
                    className="absolute left-0 top-0 h-0.5 bg-stone-900 dark:bg-zinc-100"
                    style={{
                      animation: `slideProgress ${INTERVAL_MS}ms linear forwards`,
                      animationPlayState: paused || playing ? 'paused' : 'running',
                    }}
                  />
                )}
                {!isActive && (
                  <span className="absolute left-0 top-0 h-0.5 w-full bg-stone-100 dark:bg-zinc-800" />
                )}
                <span className={`block text-[9px] font-bold uppercase tracking-widest mb-1
                  ${isActive ? 'text-stone-500 dark:text-zinc-400' : 'text-stone-300 dark:text-zinc-600'}`}>
                  {String(i + 1).padStart(2, '0')} · {s.category.split(' · ')[0]}
                </span>
                <span className={`block text-[11px] font-black uppercase leading-tight tracking-tight
                  ${isActive
                    ? 'text-stone-900 dark:text-zinc-100'
                    : 'text-stone-400 dark:text-zinc-600 group-hover:text-stone-700 dark:group-hover:text-zinc-400'}`}>
                  {s.headline.join(' ')}
                </span>
              </button>
            );
          })}
        </div>

        {/* Category */}
        <p className="text-xs font-bold uppercase tracking-widest text-stone-400 dark:text-zinc-500">
          {slide.category}
        </p>

        {/* Headline */}
        <h1 className="font-display font-black uppercase leading-[0.95] tracking-wide text-stone-900 dark:text-zinc-100 text-5xl sm:text-6xl lg:text-7xl">
          {slide.headline.map((line, i) => (
            <span key={i}>
              {line}
              {i < slide.headline.length - 1 && <br />}
            </span>
          ))}
        </h1>

        {/* Media — video or static image */}
        <div className="group/media relative aspect-video w-full overflow-hidden bg-stone-900">
          {slide.videoId && playing ? (
            <iframe
              src={`https://www.youtube.com/embed/${slide.videoId}?autoplay=1`}
              title={slide.videoTitle}
              className="absolute inset-0 h-full w-full border-0"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
              allowFullScreen
            />
          ) : slide.videoId ? (
            <>
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={thumbnailUrl}
                alt={slide.videoTitle}
                className="h-full w-full object-cover"
                onError={(e) => {
                  (e.target as HTMLImageElement).src = `https://img.youtube.com/vi/${slide.videoId}/hqdefault.jpg`;
                }}
              />
              <div className="absolute inset-0 bg-black/10 transition-colors hover:bg-black/25" />
              <button
                type="button"
                onClick={() => setPlaying(true)}
                className="absolute inset-0 flex items-center justify-center"
                aria-label="Play video"
              >
                <div className="flex h-16 w-[72px] items-center justify-center rounded-xl bg-[#FF0000] shadow-lg transition-all hover:scale-110 hover:bg-[#cc0000]">
                  <svg className="h-6 w-6 translate-x-0.5 text-white" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                    <path d="M8 5v14l11-7z" />
                  </svg>
                </div>
              </button>
            </>
          ) : slide.heroImage ? (
            <>
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={slide.heroImage}
                alt={slide.heroImageAlt ?? ''}
                className="h-full w-full object-contain bg-stone-100 dark:bg-zinc-900"
              />
            </>
          ) : null}

          {/* Prev / Next arrows — always visible on the media, appear clearly on hover */}
          {!playing && (
            <>
              <button
                type="button"
                onClick={(e) => { e.stopPropagation(); advance(-1); }}
                className="absolute left-3 top-1/2 -translate-y-1/2 flex h-10 w-10 items-center justify-center rounded-full bg-white/80 text-stone-900 shadow-md backdrop-blur-sm transition-all hover:bg-white hover:scale-105 dark:bg-zinc-800/80 dark:text-zinc-100 dark:hover:bg-zinc-700"
                aria-label="Previous slide"
              >
                <svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M15 19l-7-7 7-7" />
                </svg>
              </button>
              <button
                type="button"
                onClick={(e) => { e.stopPropagation(); advance(1); }}
                className="absolute right-3 top-1/2 -translate-y-1/2 flex h-10 w-10 items-center justify-center rounded-full bg-white/80 text-stone-900 shadow-md backdrop-blur-sm transition-all hover:bg-white hover:scale-105 dark:bg-zinc-800/80 dark:text-zinc-100 dark:hover:bg-zinc-700"
                aria-label="Next slide"
              >
                <svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M9 5l7 7-7 7" />
                </svg>
              </button>
              {/* Slide counter */}
              <div className="absolute bottom-3 right-3 rounded-full bg-black/50 px-2.5 py-1 text-[10px] font-bold tabular-nums text-white backdrop-blur-sm">
                {String(current + 1).padStart(2, '0')} / {String(SLIDES.length).padStart(2, '0')}
              </div>
            </>
          )}
        </div>

        {/* Article or external link */}
        {slide.article ? (
          <InlineArticle key={current} article={slide.article} />
        ) : slide.blogUrl ? (
          <>
            <a
              href={slide.blogUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="group flex items-start justify-between gap-4 border-t border-stone-200 pt-4 dark:border-zinc-800"
            >
              <div className="flex flex-col gap-1">
                <span className="text-[10px] font-bold uppercase tracking-widest text-stone-400 dark:text-zinc-500">
                  From the blog · {slide.blogSource}
                </span>
                <span className="text-sm font-semibold leading-snug text-stone-900 transition-colors group-hover:text-stone-500 dark:text-zinc-100 dark:group-hover:text-zinc-400">
                  {slide.blogTitle}
                </span>
              </div>
              <span className="mt-1 shrink-0 text-xs font-bold uppercase tracking-widest text-stone-400 transition-colors group-hover:text-stone-900 dark:text-zinc-500 dark:group-hover:text-zinc-100">
                Read →
              </span>
            </a>
            <p className="max-w-2xl text-sm leading-relaxed text-stone-600 dark:text-zinc-400 sm:text-base">
              {slide.blogBlurb}
            </p>
          </>
        ) : null}

        {/* CTAs */}
        <div className="flex flex-wrap items-center gap-3">
          <Link href="/telemetry" className="btn-primary">
            Explore Telemetry
          </Link>
          {slide.blogUrl && (
            <a href={slide.blogUrl} target="_blank" rel="noopener noreferrer" className="btn-outline">
              Read the Article
            </a>
          )}
        </div>

        {/* Tags */}
        <div className="flex flex-wrap gap-2">
          {slide.tags.map((tag) => (
            <span key={tag} className="tag-pill text-[11px]">
              {tag}
            </span>
          ))}
        </div>
      </div>

      {/* Right column — sidebar cards */}
      <div className="flex flex-col divide-y divide-stone-200 dark:divide-zinc-800">
        {SIDEBAR_CARDS.map((card) => {
          const inner = (
            <div className="group flex flex-col gap-2 border-t border-stone-200 dark:border-zinc-800 py-5 transition-colors hover:border-stone-900 dark:hover:border-zinc-400 cursor-pointer">
              <span className="text-2xl leading-none" aria-hidden="true">{card.icon}</span>
              <p className="font-black text-xs uppercase tracking-widest text-stone-900 dark:text-zinc-100">{card.title}</p>
              <p className="text-xs leading-relaxed text-stone-500 dark:text-zinc-500">{card.description}</p>
              <span className="text-xs font-bold uppercase tracking-widest text-stone-400 dark:text-zinc-500 transition-colors group-hover:text-stone-900 dark:group-hover:text-zinc-100">{card.cta}</span>
            </div>
          );
          if (card.external) {
            return (
              <a key={card.title} href={card.href} target="_blank" rel="noopener noreferrer" className="block">
                {inner}
              </a>
            );
          }
          return (
            <Link key={card.title} href={card.href} className="block">
              {inner}
            </Link>
          );
        })}
      </div>
    </section>
  );
}
