'use client';

import { useState, useEffect, useRef, useCallback } from 'react';
import Link from 'next/link';

interface ArticleSection {
  heading?: string;
  paragraphs: string[];
}

interface HeroArticle {
  title: string;
  subtitle: string;
  sections: ArticleSection[];
}

interface Slide {
  videoId: string;
  videoTitle: string;
  category: string;
  headline: string[];
  tags: string[];
  // Embedded article (renders inline with preview + expand)
  article?: HeroArticle;
  // External blog fallback
  blogUrl?: string;
  blogSource?: string;
  blogTitle?: string;
  blogBlurb?: string;
}

const SLIDE_ARTICLE_1: HeroArticle = {
  title: 'The Derived Ontology: From Theory to Working Migrations',
  subtitle:
    'How a canonical ontology layer turned autonomous dashboard migration from theory into a working system across ELK, LGTM, and Dash0',
  sections: [
    {
      heading: 'From Concept to Proof',
      paragraphs: [
        'In January I wrote about ontologies for vendor-agnostic observability migration — the idea that a canonical semantic layer could bridge the conceptual gaps between platforms. That post was theory. This one is about what happened when we built it and pointed it at real infrastructure.',
        'The short version: we now have autonomous, AI-driven migration of dashboards and alert rules across three observability stacks — ELK (Elasticsearch/Kibana), LGTM (Loki/Grafana/Tempo/Mimir), and Dash0 — using derived ontological mappings that an AI agent traverses at runtime. Not scripts. Not templates. An agent that reads a source dashboard, understands what each panel means, and rebuilds it idiomatically on the target platform.',
        'The demo environment is a multi-cluster k3d setup running the OpenTelemetry Demo application, with identical instrumentation feeding all three stacks simultaneously. Same traces, same spans, same services. Three completely different ways of storing and querying them.',
      ],
    },
    {
      heading: 'The Derived Ontology',
      paragraphs: [
        "Rather than a static canonical model, we derived the ontology empirically. We stood up all three platforms against the same OTel data, then systematically mapped how each one represents the same underlying reality. The ontology isn't an abstract schema — it's a set of concrete translation rules extracted from observation.",
        'Take something as simple as "show me the error rate by service." Three platforms, three completely different expressions of the same concept:',
        'Kibana (KQL + Lens aggregations): A count operation type on an otel-traces* data view with a filter column where span.status.code: 2, broken down by a terms column on Resource.service.name.',
        'Grafana (PromQL against Mimir span metrics): sum by (service) (rate(traces_spanmetrics_calls_total{status_code="STATUS_CODE_ERROR"}[5m])). Note service not service_name, and STATUS_CODE_ERROR in SCREAMING_CASE.',
        'Dash0 (PromQL against OTel synthetic metrics): sum by (service_name) (rate({__name__="dash0.spans", otel_span_status_code="Error"}[$__rate_interval])). Note service_name, Title Case "Error", the __name__ selector syntax, and mandatory $__rate_interval.',
        'Same intent. Three different metric names, label keys, label values, query languages, and structural conventions. A syntactic converter would need to handle each pair independently — six translation paths for three platforms. The ontology reduces this to three mappings against a canonical concept: "error rate grouped by service identity."',
      ],
    },
    {
      heading: 'What the Mapping Actually Looks Like',
      paragraphs: [
        "The derived ontology isn't a single document. It's a layered system of translation tables that an AI agent consults during migration. Here's what we found we needed:",
        'Metric identity mapping. The same underlying data (OTel spans) surfaces as completely different metric names across platforms. Kibana doesn\'t have "metrics" at all — it queries raw span documents. Grafana\'s Mimir has traces_spanmetrics_calls_total generated by Tempo\'s span metrics processor. Dash0 synthesizes {__name__="dash0.spans"} at query time. Three paradigms: document store, derived counter, synthetic metric.',
        'Label key mapping. The service that emitted a span is Resource.service.name in Elasticsearch documents, service in Mimir span metrics labels, and service_name in Dash0. The service → service_name mapping between Grafana and Dash0 turned out to be the single most common migration error in testing — easy to miss, silent failure.',
        'Label value mapping. OTel span status codes appear as integer 2 in Elasticsearch, STATUS_CODE_ERROR in Mimir, and "Error" (Title Case) in Dash0. Wrong case returns zero results with no error. This is the kind of thing that burns hours in a manual migration and takes seconds to encode in an ontology.',
        'Structural mapping. Kibana Lens packs visualization config, query logic, and column definitions into a deeply nested JSON structure with layer IDs and operation types. Grafana uses flat PromQL strings with gridPos on each panel. Dash0 uses Perses CRDs with separate panels[] and layouts[] arrays, grid items referencing panels by index. The AI needs to understand all three structural idioms to translate between them.',
        'Query pattern mapping. increase(...[1h]) is idiomatic Grafana but invalid in Dash0\'s Perses context — you need rate(...[$__rate_interval]) * 3600. count in Kibana Lens is a document aggregation; in PromQL it\'s an entirely different operation. topk() works fine in Grafana but breaks Dash0 panels when the inner query returns no series.',
      ],
    },
    {
      heading: 'Gap Analysis in Practice',
      paragraphs: [
        'The original post predicted that gap detection would be the killer feature. It is.',
        'When migrating a Kibana dashboard that breaks spans down by span.name (operation name), the ontology flags: "span name is not available as a PromQL label in Dash0 — too-high cardinality. Substitute with http_route or rpc_method depending on protocol." The agent doesn\'t silently drop the panel or generate a broken query. It makes an informed substitution and documents the change.',
        "Similarly, Grafana's service graph metrics (traces_service_graph_request_total with client/server labels) have no equivalent in Dash0. The ontology maps this to RPC service/method groupings as the closest available approximation, and the gap is documented in the migration output.",
        "Some gaps we discovered weren't in the ontology theory at all — they're API-level behaviors that only surface through empirical testing:",
        "Dash0's dashboards_create API silently drops the layouts field. You must immediately follow creation with an update call containing the same payload. Without this, you get panel titles but empty tiles. No error, no warning. This took real debugging hours to discover and is now encoded in the migration skill so the agent handles it automatically every time.",
        "Dash0's check rule API uses otel_metric_name as the metric selector — not __name__. Dashboard PromQL uses __name__. Same platform, two different selector syntaxes for the same underlying metric. The ontology captures this distinction.",
        'Status code values in check rules are "ERROR" (uppercase), while in dashboard PromQL they\'re "Error" (Title Case). Same label, same platform, different casing depending on context.',
      ],
    },
    {
      heading: 'The Agent Architecture',
      paragraphs: [
        'The migration isn\'t a script. It\'s an AI agent equipped with MCP (Model Context Protocol) servers for each platform — Kibana, Elasticsearch, Grafana, and Dash0 — plus the derived ontology encoded as structured documentation the agent reads before executing.',
        'The workflow for a Kibana → Dash0 dashboard migration: The agent lists source dashboards via kibana_dashboards_list, presents options, and extracts the selected dashboard\'s full definition. It resolves data views to understand whether panels query spans or logs. Then — critically — it samples live data from the Dash0 environment via dash0_spans_query to confirm which labels actually exist in the target before building any panels.',
        'For each Kibana Lens panel, the agent reads the visualization type (XY, pie, metric, table), the operation types (count, average, percentile, terms), the source fields, and any filters. It maps each element through the ontology: Lens lnsXY becomes TimeSeriesChart, a count operation on traces becomes sum(rate({__name__="dash0.spans"}[$__rate_interval])), a terms breakdown on service.name becomes a by (service_name) clause.',
        'The agent assembles the Perses CRD, handles the two-step create-then-update dance, and verifies the result. If panels show "no data," it can query Dash0\'s live span data to diagnose the issue — wrong label name, wrong case, missing filter — and fix it autonomously.',
        'The same architecture handles Grafana → Dash0 with different translation tables. The LGTM metric names, label keys, and query patterns map through the same canonical concepts to different Dash0 expressions.',
      ],
    },
    {
      heading: 'What We Learned',
      paragraphs: [
        'The ontology is never complete on the first pass. We started with theoretical mappings and refined them through actual migration attempts. Every "no data" panel in the target platform exposed a mapping gap we hadn\'t anticipated. The 21 "hard-won lessons" documented in our migration skills are battle scars from this process.',
        'Label cardinality determines what\'s possible. High-cardinality fields like span name and span kind are available in Kibana (document-level queries) but absent from PromQL-based platforms where they\'d create metric explosion. The ontology must encode these availability boundaries, not just name mappings.',
        'API behavior matters as much as data model. The layouts silently dropping, the __name__ vs otel_metric_name split, the case sensitivity of status code values — these are implementation details that no theoretical ontology would predict. They only emerge from empirical testing and must be captured for autonomous operation.',
        "Log severity is sparser than you expect. Many services write raw stdout logs without OTel severity metadata. A dashboard that segments logs by severity will show nothing for most services. The ontology now defaults to total log volume by service, using severity breakdowns only when confirmed present in the target environment.",
        "The two-platform problem is deceptive. Going from Kibana to Dash0 requires one mapping. Adding Grafana as a source requires a second, largely independent mapping — the LGTM stack's data model differs from both ELK and Dash0. But once you have both, you also implicitly have Kibana → Grafana (which we built separately and validated). The ontology's value compounds as platforms are added.",
      ],
    },
    {
      heading: 'What This Means for Observability Consulting',
      paragraphs: [
        'Traditional migration engagements rely on senior engineers manually inspecting source configurations, understanding intent, and rebuilding in the target platform. It works, but it\'s slow and the quality depends entirely on who\'s doing the work.',
        'With the derived ontology and agent architecture, the mechanical translation is automated. The 22-panel dashboard migration that would take a consultant a day completes in minutes. The consultant\'s expertise focuses on the gaps — the panels that can\'t translate cleanly, the architectural decisions about what to substitute, the trade-offs between fidelity and capability.',
        'This isn\'t "AI replaces the consultant." It\'s "AI handles the conversion work so the consultant focuses on the decisions that actually require judgment." The ontology surfaces those decisions explicitly rather than leaving them buried in implementation details that might not be discovered until production.',
        "The migration skills and ontological mappings are living documents. Every new engagement, every new platform version, every edge case feeds back into the system. The agent gets better at migration the same way a consulting team builds institutional knowledge — except the knowledge is encoded, reproducible, and doesn't walk out the door.",
      ],
    },
  ],
};

// Add more slides here when new videos are published
const SLIDES: Slide[] = [
  {
    videoId: 'hlS44t0_z0M',
    videoTitle: 'Agentic Workflow — Kibana to Grafana Dashboard Migration',
    category: 'Observability · Platform Engineering',
    headline: ['THE DERIVED', 'ONTOLOGY:', 'MIGRATIONS AT SCALE'],
    tags: ['OpenTelemetry', 'Agentic AI', 'Platform Migration', 'MCP'],
    article: SLIDE_ARTICLE_1,
  },
];

const SIDEBAR_CARDS = [
  {
    icon: '🔭',
    title: 'LIVE TELEMETRY',
    description: 'Real-time traces and metrics from this running application.',
    cta: 'Explore →',
    href: '/telemetry',
    external: false,
  },
  {
    icon: '🤖',
    title: 'VALIS MCP',
    description:
      'AI-native observability tool for Claude — trace analysis, anomaly detection, root cause correlation.',
    cta: 'View on GitHub →',
    href: 'https://github.com/npcomplete777/valis-mcp',
    external: true,
  },
  {
    icon: '⚡',
    title: 'SOURCE CODE',
    description: 'Full-stack Kubernetes app: Next.js, Spring Boot, OTel Java agent.',
    cta: 'View on GitHub →',
    href: 'https://github.com/npcomplete777/my-news-k8s',
    external: true,
  },
];

const INTERVAL_MS = 5000;
const PREVIEW_PARAGRAPHS = 2;

function InlineArticle({ article }: { article: HeroArticle }) {
  const [expanded, setExpanded] = useState(false);

  const previewParas = article.sections[0]?.paragraphs.slice(0, PREVIEW_PARAGRAPHS) ?? [];

  return (
    <div className="border-t border-stone-200 pt-4 dark:border-zinc-800">
      {/* Header */}
      <div className="mb-3 flex flex-col gap-1">
        <span className="text-[10px] font-bold uppercase tracking-widest text-stone-400 dark:text-zinc-500">
          Featured Article · O11y Alchemy
        </span>
        <h2 className="text-base font-black uppercase tracking-tight text-stone-900 dark:text-zinc-100 sm:text-lg">
          {article.title}
        </h2>
        <p className="text-xs font-medium italic text-stone-500 dark:text-zinc-500">
          {article.subtitle}
        </p>
      </div>

      {/* Collapsed preview */}
      {!expanded && (
        <div className="flex flex-col gap-3">
          {previewParas.map((para, i) => (
            <p key={i} className="text-sm leading-relaxed text-stone-600 dark:text-zinc-400">
              {para}
            </p>
          ))}
          <button
            type="button"
            onClick={() => setExpanded(true)}
            className="mt-1 self-start text-xs font-bold uppercase tracking-widest text-stone-900 underline underline-offset-4 transition-colors hover:text-stone-500 dark:text-zinc-100 dark:hover:text-zinc-400"
          >
            Read full article ↓
          </button>
        </div>
      )}

      {/* Expanded full article */}
      {expanded && (
        <div className="flex flex-col gap-6">
          {article.sections.map((section, si) => (
            <div key={si} className="flex flex-col gap-3">
              {section.heading && (
                <h3 className="text-xs font-black uppercase tracking-widest text-stone-900 dark:text-zinc-100">
                  {section.heading}
                </h3>
              )}
              {section.paragraphs.map((para, pi) => (
                <p key={pi} className="text-sm leading-relaxed text-stone-600 dark:text-zinc-400">
                  {para}
                </p>
              ))}
            </div>
          ))}
          <button
            type="button"
            onClick={() => setExpanded(false)}
            className="self-start text-xs font-bold uppercase tracking-widest text-stone-400 underline underline-offset-4 transition-colors hover:text-stone-900 dark:text-zinc-500 dark:hover:text-zinc-100"
          >
            Collapse ↑
          </button>
        </div>
      )}
    </div>
  );
}

export function HeroCarousel() {
  const [current, setCurrent] = useState(0);
  const [playing, setPlaying] = useState(false);
  const [paused, setPaused] = useState(false);
  const [progressKey, setProgressKey] = useState(0);
  const timerRef = useRef<ReturnType<typeof setTimeout>>(null);

  const advance = useCallback((dir: number) => {
    setCurrent((c) => (c + dir + SLIDES.length) % SLIDES.length);
    setPlaying(false);
    setProgressKey((k) => k + 1);
  }, []);

  const goTo = useCallback((idx: number) => {
    setCurrent(idx);
    setPlaying(false);
    setProgressKey((k) => k + 1);
  }, []);

  useEffect(() => {
    if (paused || playing) return;
    timerRef.current = setTimeout(() => advance(1), INTERVAL_MS);
    return () => {
      if (timerRef.current) clearTimeout(timerRef.current);
    };
  }, [current, paused, playing, progressKey, advance]);

  const slide = SLIDES[current];
  const thumbnailUrl = `https://img.youtube.com/vi/${slide.videoId}/maxresdefault.jpg`;

  return (
    <section
      className="grid grid-cols-1 gap-10 py-10 lg:grid-cols-[1fr_300px]"
      onMouseEnter={() => setPaused(true)}
      onMouseLeave={() => setPaused(false)}
    >
      {/* Left column */}
      <div className="flex flex-col gap-6">
        {/* Progress indicators */}
        <div className="flex gap-2">
          {SLIDES.map((_, i) => (
            <button
              key={i}
              type="button"
              onClick={() => goTo(i)}
              className="relative h-0.5 flex-1 overflow-hidden bg-stone-200 dark:bg-zinc-800"
              aria-label={`Go to slide ${i + 1}`}
            >
              {i < current && (
                <span className="absolute inset-0 bg-stone-900 dark:bg-zinc-100" />
              )}
              {i === current && (
                <span
                  key={progressKey}
                  className="absolute inset-y-0 left-0 bg-stone-900 dark:bg-zinc-100"
                  style={{
                    animation: `slideProgress ${INTERVAL_MS}ms linear forwards`,
                    animationPlayState: paused || playing ? 'paused' : 'running',
                  }}
                />
              )}
            </button>
          ))}
        </div>

        {/* Category */}
        <p className="text-xs font-bold uppercase tracking-widest text-stone-400 dark:text-zinc-500">
          {slide.category}
        </p>

        {/* Headline */}
        <h1 className="font-display font-black uppercase leading-none tracking-tighter text-stone-900 dark:text-zinc-100 text-4xl sm:text-5xl lg:text-6xl">
          {slide.headline.map((line, i) => (
            <span key={i}>
              {line}
              {i < slide.headline.length - 1 && <br />}
            </span>
          ))}
        </h1>

        {/* Video */}
        <div className="relative aspect-video w-full overflow-hidden bg-stone-900">
          {playing ? (
            <iframe
              src={`https://www.youtube.com/embed/${slide.videoId}?autoplay=1`}
              title={slide.videoTitle}
              className="absolute inset-0 h-full w-full border-0"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
              allowFullScreen
            />
          ) : (
            <>
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={thumbnailUrl}
                alt={slide.videoTitle}
                className="h-full w-full object-cover"
                onError={(e) => {
                  (e.target as HTMLImageElement).src = `https://img.youtube.com/vi/${slide.videoId}/hqdefault.jpg`;
                }}
              />
              <div className="absolute inset-0 bg-black/10 transition-colors hover:bg-black/25" />
              <button
                type="button"
                onClick={() => setPlaying(true)}
                className="absolute inset-0 flex items-center justify-center"
                aria-label="Play video"
              >
                <div className="flex h-16 w-[72px] items-center justify-center rounded-xl bg-[#FF0000] shadow-lg transition-all hover:scale-110 hover:bg-[#cc0000]">
                  <svg className="h-6 w-6 translate-x-0.5 text-white" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                    <path d="M8 5v14l11-7z" />
                  </svg>
                </div>
              </button>
              <button
                type="button"
                onClick={(e) => { e.stopPropagation(); advance(-1); }}
                className="absolute left-3 top-1/2 -translate-y-1/2 flex h-9 w-9 items-center justify-center rounded-full bg-black/40 text-white backdrop-blur-sm transition-colors hover:bg-black/60"
                aria-label="Previous slide"
              >
                <svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
                </svg>
              </button>
              <button
                type="button"
                onClick={(e) => { e.stopPropagation(); advance(1); }}
                className="absolute right-3 top-1/2 -translate-y-1/2 flex h-9 w-9 items-center justify-center rounded-full bg-black/40 text-white backdrop-blur-sm transition-colors hover:bg-black/60"
                aria-label="Next slide"
              >
                <svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                </svg>
              </button>
            </>
          )}
        </div>

        {/* Article or external link */}
        {slide.article ? (
          <InlineArticle key={current} article={slide.article} />
        ) : slide.blogUrl ? (
          <>
            <a
              href={slide.blogUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="group flex items-start justify-between gap-4 border-t border-stone-200 pt-4 dark:border-zinc-800"
            >
              <div className="flex flex-col gap-1">
                <span className="text-[10px] font-bold uppercase tracking-widest text-stone-400 dark:text-zinc-500">
                  From the blog · {slide.blogSource}
                </span>
                <span className="text-sm font-semibold leading-snug text-stone-900 transition-colors group-hover:text-stone-500 dark:text-zinc-100 dark:group-hover:text-zinc-400">
                  {slide.blogTitle}
                </span>
              </div>
              <span className="mt-1 shrink-0 text-xs font-bold uppercase tracking-widest text-stone-400 transition-colors group-hover:text-stone-900 dark:text-zinc-500 dark:group-hover:text-zinc-100">
                Read →
              </span>
            </a>
            <p className="max-w-2xl text-sm leading-relaxed text-stone-600 dark:text-zinc-400 sm:text-base">
              {slide.blogBlurb}
            </p>
          </>
        ) : null}

        {/* CTAs */}
        <div className="flex flex-wrap items-center gap-3">
          <Link href="/telemetry" className="btn-primary">
            Explore Telemetry
          </Link>
          {slide.blogUrl && (
            <a href={slide.blogUrl} target="_blank" rel="noopener noreferrer" className="btn-outline">
              Read the Article
            </a>
          )}
        </div>

        {/* Tags */}
        <div className="flex flex-wrap gap-2">
          {slide.tags.map((tag) => (
            <span key={tag} className="tag-pill text-[11px]">
              {tag}
            </span>
          ))}
        </div>
      </div>

      {/* Right column — sidebar cards */}
      <div className="flex flex-col divide-y divide-stone-200 dark:divide-zinc-800">
        {SIDEBAR_CARDS.map((card) => {
          const inner = (
            <div className="group flex flex-col gap-2 border-t border-stone-200 dark:border-zinc-800 py-5 transition-colors hover:border-stone-900 dark:hover:border-zinc-400 cursor-pointer">
              <span className="text-2xl leading-none" aria-hidden="true">{card.icon}</span>
              <p className="font-black text-xs uppercase tracking-widest text-stone-900 dark:text-zinc-100">{card.title}</p>
              <p className="text-xs leading-relaxed text-stone-500 dark:text-zinc-500">{card.description}</p>
              <span className="text-xs font-bold uppercase tracking-widest text-stone-400 dark:text-zinc-500 transition-colors group-hover:text-stone-900 dark:group-hover:text-zinc-100">{card.cta}</span>
            </div>
          );
          if (card.external) {
            return (
              <a key={card.title} href={card.href} target="_blank" rel="noopener noreferrer" className="block">
                {inner}
              </a>
            );
          }
          return (
            <Link key={card.title} href={card.href} className="block">
              {inner}
            </Link>
          );
        })}
      </div>
    </section>
  );
}
