{{- if and .Values.localOtel.enabled .Values.localOtel.prometheus.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "o11y-news.fullname" . }}-prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "o11y-news.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: otelcol
        static_configs:
          - targets: ['otelcol:8889']
        relabel_configs:
          - source_labels: [__address__]
            target_label: instance
            replacement: otelcol
{{- end }}
