apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "o11y-news.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "o11y-news.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
