{{- if .Values.localOtel.clickhouse.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "o11y-news.labels" . | nindent 4 }}
    app.kubernetes.io/component: clickhouse
spec:
  type: ClusterIP
  selector:
    {{- include "o11y-news.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: clickhouse
  ports:
    - name: http
      port: 8123
      targetPort: http
    - name: native
      port: 9000
      targetPort: native
{{- end }}
