apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: argocd
spec:
  description: The Self-Observing Observatory
  sourceRepos:
    - https://github.com/npcomplete777/my-news-k8s.git
  destinations:
    - namespace: o11y-news
      server: https://kubernetes.default.svc
    - namespace: dash0-system
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: networking.k8s.io
      kind: IngressClass
